version: "3.8"

services:
  mymongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "pass123"

  backend:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mymongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/healthCheck", "||", "exit 1"]
      interval: 20s #specifies the seconds to initially wait before executing the health check and for the subsequent checks
      timeout: 5s
      retries: 3
      start_period: 25s #health checks with an exit code greater than zero won’t mark the container as unhealthy; however, a status code of 0 will mark the container as healthy.

  backend-tests:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: ./backend
    command:
      - /bin/sh
      - -c
      - |
        ls -R __tests__
        npm run test
    working_dir: /app
    depends_on:
      - mymongodb
      - backend

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  src:
