version: "3.8"

services:
  mymongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "pass123"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mymongodb

  backend-tests:
    build: ./backend
    command:
      - /bin/sh
      - -c
      - |
        ls -R __tests__
        npm run test
    working_dir: /app
    depends_on:
      - mymongodb
      - backend

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  src:
