name: CI/CD Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      # Downgrade to Docker Compose V1, since there is a bug where `docker compose` commands are not captured (issue 9104)
      COMPOSE_DOCKER_CLI_BUILD: 0
      DOCKER_SCAN_SUGGEST: false

    # Steps represent a sequence of tasks that will be executed as part of the job
    # Each job in a workflow runs in a fresh virtual environment managed by GitHub.
    steps:
      # Checks-out to the GitHub's predefined/pre-created actions directory, where all the actions are 'hosted'
      - name: Checkout code
        # https://github.com/actions/checkout
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run Docker Compose, Check Containers and Run tests
        run: |
          chmod +x scripts/ci-scripts/docker-compose-test.sh
          ./scripts/ci-scripts/docker-compose-test.sh

      - name: Upload log file
        uses: actions/upload-artifact@v3
        # Uploads the artifact even if the build fails
        if: always()
        with:
          name: docker-compose-logs
          path: scripts/ci-scripts/docker_compose_logs.log